CREATE TABLE "parsed_emails" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"email_id" varchar(255) NOT NULL,
	"message_id" varchar(255),
	"from_text" text,
	"from_address" varchar(255),
	"from_name" varchar(255),
	"to_text" text,
	"to_addresses" text,
	"cc_text" text,
	"cc_addresses" text,
	"bcc_text" text,
	"bcc_addresses" text,
	"reply_to_text" text,
	"reply_to_addresses" text,
	"subject" text,
	"text_body" text,
	"html_body" text,
	"in_reply_to" varchar(255),
	"references" text,
	"priority" varchar(50),
	"email_date" timestamp,
	"attachments" text,
	"attachment_count" integer DEFAULT 0,
	"has_attachments" boolean DEFAULT false,
	"headers" text,
	"has_text_body" boolean DEFAULT false,
	"has_html_body" boolean DEFAULT false,
	"parse_success" boolean DEFAULT true,
	"parse_error" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
