CREATE TABLE "structured_emails" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"email_id" varchar(255) NOT NULL,
	"ses_event_id" varchar(255) NOT NULL,
	"message_id" varchar(255),
	"date" timestamp,
	"subject" text,
	"from_data" text,
	"to_data" text,
	"cc_data" text,
	"bcc_data" text,
	"reply_to_data" text,
	"in_reply_to" varchar(255),
	"references" text,
	"text_body" text,
	"html_body" text,
	"raw_content" text,
	"attachments" text,
	"headers" text,
	"priority" varchar(50),
	"parse_success" boolean DEFAULT true,
	"parse_error" text,
	"user_id" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
