CREATE TABLE "sent_emails" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"from" varchar(500) NOT NULL,
	"from_address" varchar(255) NOT NULL,
	"from_domain" varchar(255) NOT NULL,
	"to" text NOT NULL,
	"cc" text,
	"bcc" text,
	"reply_to" text,
	"subject" text NOT NULL,
	"text_body" text,
	"html_body" text,
	"headers" text,
	"attachments" text,
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"message_id" varchar(255),
	"provider" varchar(50) DEFAULT 'ses',
	"provider_response" text,
	"sent_at" timestamp,
	"failure_reason" text,
	"idempotency_key" varchar(256),
	"user_id" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
