CREATE TABLE "scheduled_emails" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"scheduled_at" timestamp NOT NULL,
	"timezone" varchar(50) DEFAULT 'UTC',
	"status" varchar(50) DEFAULT 'scheduled' NOT NULL,
	"from_address" varchar(500) NOT NULL,
	"from_domain" varchar(255) NOT NULL,
	"to_addresses" text NOT NULL,
	"cc_addresses" text,
	"bcc_addresses" text,
	"reply_to_addresses" text,
	"subject" text NOT NULL,
	"text_body" text,
	"html_body" text,
	"headers" text,
	"attachments" text,
	"tags" text,
	"attempts" integer DEFAULT 0,
	"max_attempts" integer DEFAULT 3,
	"next_retry_at" timestamp,
	"last_error" text,
	"idempotency_key" varchar(256),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"sent_at" timestamp,
	"sent_email_id" varchar(255)
);
