import type { MailContact, MailThread } from "@/lib/mail-types";

const ryan: MailContact = { name: "Ryan Vogel", email: "ryan@inbound.new" };
const maya: MailContact = { name: "Maya Chen", email: "maya@northstar.studio" };
const jon: MailContact = { name: "Jon Bell", email: "jon@linear.app" };
const priya: MailContact = { name: "Priya Shah", email: "priya@meridian.dev" };
const finance: MailContact = { name: "Ramp", email: "receipts@ramp.com" };
const github: MailContact = { name: "GitHub", email: "notifications@github.com" };
const vercel: MailContact = { name: "Vercel", email: "notifications@vercel.com" };
const sam: MailContact = { name: "Sam Rivera", email: "sam@paper.co" };
const apple: MailContact = { name: "Apple", email: "no_reply@apple.com" };

export const MOCK_THREADS: MailThread[] = [
	{
		id: "thread-northstar",
		subject: "The launch page is ready",
		snippet: "I pushed the last pass. The mobile spacing feels much calmer now…",
		participants: [maya],
		lastMessageAt: "2026-08-01T21:42:00.000Z",
		messageCount: 3,
		unread: true,
		starred: true,
		important: true,
		folder: "inbox",
		category: "team",
		labels: ["Design"],
		messages: [
			{
				id: "message-northstar-1",
				threadId: "thread-northstar",
				direction: "inbound",
				from: maya,
				to: [ryan],
				sentAt: "2026-07-31T17:18:00.000Z",
				bodyText:
					"Hey Ryan,\n\nThe launch page is ready for a final look. I simplified the hero, tightened the product shots, and removed the extra comparison section. It feels much more direct now.\n\nMaya",
				attachments: [
					{ id: "attachment-launch", name: "launch-final.pdf", size: "2.4 MB", type: "pdf" },
				],
			},
			{
				id: "message-northstar-2",
				threadId: "thread-northstar",
				direction: "outbound",
				from: ryan,
				to: [maya],
				sentAt: "2026-08-01T14:10:00.000Z",
				bodyText:
					"This is close. Can we give the mobile version a little more air around the primary action? Everything else is landing really well.",
			},
			{
				id: "message-northstar-3",
				threadId: "thread-northstar",
				direction: "inbound",
				from: maya,
				to: [ryan],
				sentAt: "2026-08-01T21:42:00.000Z",
				bodyText:
					"Done — I pushed the last pass. The mobile spacing feels much calmer now, and I checked it across the small iPhone breakpoints. You can ship this version.",
			},
		],
	},
	{
		id: "thread-linear",
		subject: "A faster way through the inbox",
		snippet: "The command menu prototype is attached. J/K navigation is feeling instant.",
		participants: [jon],
		lastMessageAt: "2026-08-01T19:20:00.000Z",
		messageCount: 2,
		unread: true,
		starred: false,
		important: true,
		folder: "inbox",
		category: "important",
		labels: ["Product"],
		messages: [
			{
				id: "message-linear-1",
				threadId: "thread-linear",
				direction: "outbound",
				from: ryan,
				to: [jon],
				sentAt: "2026-08-01T17:02:00.000Z",
				bodyText: "I want the inbox to disappear beneath the keyboard. What is the smallest command set that gets us there?",
			},
			{
				id: "message-linear-2",
				threadId: "thread-linear",
				direction: "inbound",
				from: jon,
				to: [ryan],
				sentAt: "2026-08-01T19:20:00.000Z",
				bodyText:
					"Start with J/K, E, S, R, C, and command search. The command menu prototype is attached. J/K navigation is feeling instant, and the whole thing works without making the UI look like a cockpit.",
				attachments: [
					{ id: "attachment-shortcuts", name: "keyboard-map.png", size: "486 KB", type: "image" },
				],
			},
		],
	},
	{
		id: "thread-meridian",
		subject: "Friday notes and next steps",
		snippet: "Three decisions, one open question, and no meeting needed.",
		participants: [priya, sam],
		lastMessageAt: "2026-08-01T16:48:00.000Z",
		messageCount: 4,
		unread: false,
		starred: false,
		important: false,
		folder: "inbox",
		category: "team",
		labels: ["Team"],
		messages: [
			{
				id: "message-meridian-1",
				threadId: "thread-meridian",
				direction: "inbound",
				from: priya,
				to: [ryan, sam],
				sentAt: "2026-08-01T16:48:00.000Z",
				bodyText:
					"Friday notes:\n\n1. Keep onboarding to one screen.\n2. Default notifications to important only.\n3. Ship the keyboard map with the first release.\n\nOpen question: should archive happen automatically after reply? No meeting needed — reply in thread when you have a preference.",
			},
		],
	},
	{
		id: "thread-vercel",
		subject: "Deployment completed",
		snippet: "Production is live. Build time 41s.",
		participants: [vercel],
		lastMessageAt: "2026-08-01T15:31:00.000Z",
		messageCount: 1,
		unread: false,
		starred: false,
		important: false,
		folder: "inbox",
		category: "updates",
		labels: [],
		messages: [
			{
				id: "message-vercel-1",
				threadId: "thread-vercel",
				direction: "inbound",
				from: vercel,
				to: [ryan],
				sentAt: "2026-08-01T15:31:00.000Z",
				bodyText: "Production is live. Build time 41s. Commit 59f5ae8 was deployed successfully to inbound.new.",
			},
		],
	},
	{
		id: "thread-ramp",
		subject: "Your July statement",
		snippet: "Your statement is ready. Total spend: $3,284.19.",
		participants: [finance],
		lastMessageAt: "2026-08-01T13:05:00.000Z",
		messageCount: 1,
		unread: true,
		starred: false,
		important: false,
		folder: "inbox",
		category: "receipts",
		labels: ["Finance"],
		messages: [
			{
				id: "message-ramp-1",
				threadId: "thread-ramp",
				direction: "inbound",
				from: finance,
				to: [ryan],
				sentAt: "2026-08-01T13:05:00.000Z",
				bodyText: "Your July statement is ready. Total spend was $3,284.19 across 24 transactions.",
				attachments: [
					{ id: "attachment-statement", name: "July-statement.pdf", size: "184 KB", type: "pdf" },
				],
			},
		],
	},
	{
		id: "thread-github",
		subject: "[inbound] 4 checks passed",
		snippet: "All checks have passed on agent/sign-in-with-inbound.",
		participants: [github],
		lastMessageAt: "2026-08-01T11:56:00.000Z",
		messageCount: 1,
		unread: false,
		starred: false,
		important: false,
		folder: "archive",
		category: "updates",
		labels: ["GitHub"],
		messages: [
			{
				id: "message-github-1",
				threadId: "thread-github",
				direction: "inbound",
				from: github,
				to: [ryan],
				sentAt: "2026-08-01T11:56:00.000Z",
				bodyText: "All checks have passed on agent/sign-in-with-inbound. The branch is ready to merge.",
			},
		],
	},
	{
		id: "thread-apple",
		subject: "Your receipt from Apple",
		snippet: "iCloud+ with 2 TB of storage — $9.99",
		participants: [apple],
		lastMessageAt: "2026-07-31T22:04:00.000Z",
		messageCount: 1,
		unread: false,
		starred: false,
		important: false,
		folder: "archive",
		category: "receipts",
		labels: ["Receipts"],
		messages: [
			{
				id: "message-apple-1",
				threadId: "thread-apple",
				direction: "inbound",
				from: apple,
				to: [ryan],
				sentAt: "2026-07-31T22:04:00.000Z",
				bodyText: "iCloud+ with 2 TB of storage\n\nRenews August 31, 2026\nTotal: $9.99",
			},
		],
	},
	{
		id: "thread-sam-snoozed",
		subject: "Coffee next week?",
		snippet: "Tuesday morning works on my side.",
		participants: [sam],
		lastMessageAt: "2026-07-30T16:11:00.000Z",
		messageCount: 2,
		unread: false,
		starred: false,
		important: false,
		folder: "snoozed",
		category: "important",
		labels: ["Personal"],
		snoozedUntil: "2026-08-04T13:00:00.000Z",
		messages: [
			{
				id: "message-sam-1",
				threadId: "thread-sam-snoozed",
				direction: "inbound",
				from: sam,
				to: [ryan],
				sentAt: "2026-07-30T16:11:00.000Z",
				bodyText: "Tuesday morning works on my side. Same place around 9?",
			},
		],
	},
	{
		id: "thread-sent-intro",
		subject: "Intro: Maya × Priya",
		snippet: "You two should know each other — I’ll let you take it from here.",
		participants: [maya, priya],
		lastMessageAt: "2026-07-29T18:20:00.000Z",
		messageCount: 1,
		unread: false,
		starred: false,
		important: false,
		folder: "sent",
		category: "team",
		labels: [],
		messages: [
			{
				id: "message-intro-1",
				threadId: "thread-sent-intro",
				direction: "outbound",
				from: ryan,
				to: [maya, priya],
				sentAt: "2026-07-29T18:20:00.000Z",
				bodyText: "Maya, Priya — you two should know each other. You are both thinking about calm interfaces for high-volume work. I’ll let you take it from here.",
			},
		],
	},
	{
		id: "thread-draft-roadmap",
		subject: "August roadmap",
		snippet: "Draft: The goal for August is simple…",
		participants: [priya],
		lastMessageAt: "2026-07-29T14:00:00.000Z",
		messageCount: 1,
		unread: false,
		starred: false,
		important: false,
		folder: "drafts",
		category: "team",
		labels: ["Draft"],
		messages: [
			{
				id: "message-draft-1",
				threadId: "thread-draft-roadmap",
				direction: "outbound",
				from: ryan,
				to: [priya],
				sentAt: "2026-07-29T14:00:00.000Z",
				bodyText: "The goal for August is simple: make every common action feel immediate.",
			},
		],
	},
	{
		id: "thread-spam",
		subject: "You have been selected!!!",
		snippet: "Claim your exclusive business award before midnight.",
		participants: [{ name: "Business Awards", email: "winner@not-a-real-award.example" }],
		lastMessageAt: "2026-07-28T09:22:00.000Z",
		messageCount: 1,
		unread: true,
		starred: false,
		important: false,
		folder: "spam",
		category: "updates",
		labels: [],
		messages: [
			{
				id: "message-spam-1",
				threadId: "thread-spam",
				direction: "inbound",
				from: { name: "Business Awards", email: "winner@not-a-real-award.example" },
				to: [ryan],
				sentAt: "2026-07-28T09:22:00.000Z",
				bodyText: "Claim your exclusive business award before midnight.",
			},
		],
	},
];

export function freshMockThreads(): MailThread[] {
	return structuredClone(MOCK_THREADS);
}
